#!/usr/bin/perl

shift =~ /(.*?)(?:\.c\+\+)?$/;
my $name = $1;
$name =~ s/'/'\\\\''/g;

!system("g++-4.5 -O3 -pg -Irise/src -std=gnu++0x -Wall -Wno-parentheses -Wno-reorder -lgc -lgccpp -lSDL -lSDL_image -lGL -lGLU -o '$name' '$name.c++'")
and exec("'./$name'");

